FROM golang:1.20.3-alpine3.17 AS build

WORKDIR /app

COPY . .

RUN CGO_ENABLED=0 go build -o client cmd/client/main.go

FROM alpine:3.17

WORKDIR /app

COPY --from=build /app/client .

ENTRYPOINT ["./client"]